package com.dam.gametoday;

//TODO: ACTIVITY PERFIL
//TODO: ELEGIR SACAR FOTO AL ELEGIR IMAGEN
//TODO: MOVER BOTON BORRAR PUBLI
//TODO: OPCIONES PUBLI BORRAR Y EDITAR
//TODO: COMENTARIOS PUBLI
//TODO: SEGUIR USUARIOS

