package com.dam.gametoday;

//TODO: MENU PUBLI BORRAR Y EDITAR
//TODO: MENU USUARIO
//TODO: btnEditarPerfil
//TODO: DIALOG ABRIR CHAT
//TODO: MENSAJES DISTINGUIR SI SE HAN LEIDO O NO
//TODO: COMENTARIOS PUBLI
//TODO: FOTOS DE GALERIA Y DE CAMARA
//TODO: MENSAJES IMAGENES
//TODO: MENSAJES PUBLICACIONES